on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install NASM
        run: sudo apt-get update && sudo apt-get install -y nasm
      
      - name: Check Formatting
        run: ./scripts/check_format.sh

      - name: Build Project
        run: ./scripts/build.sh
      
      - name: Test Project
        run: ./scripts/test.sh